version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Instalando dependencias"
      - pip install --upgrade pip
  build:
    commands:
      - echo "Empaquetando la funcion Lambda"
      - zip lambda_package.zip lambda_function.py
artifacts:
  files:
    - lambda_package.zip
