version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Instalando dependencias"
      - pip install --upgrade pip
  build:
    commands:
      - aws cloudformation validate-template --template-body file://lambdaiac.yml      
artifacts:
  files:
    - lambdaiac.yml
