version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Instalando dependencias"
      - pip install --upgrade pip
      - pip install awscli
  build:
    commands:
      - echo "Empaquetando la funcion Lambda"
      - zip lambda_package.zip lambda_function.py
      - aws cloudformation validate-template --template-body file://lambdaiac.yml
      - aws s3 cp lambda_package.zip s3://s3jjr/codebuild/artifacts/
artifacts:
  files:
    - lambdaiac.yml
